{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 3}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture\n    def common_function():\n>       name = input(\"Enter your name: \")\n\ntest_demo3.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <_pytest.capture.DontReadFromInput object at 0x0000015F7FCABDD0>, size = -1\n\n    def read(self, size: int = -1) -> str:\n>       raise OSError(\n            \"pytest: reading from stdin while output is captured!  Consider using `-s`.\"\n        )\nE       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n\n..\\venv\\Lib\\site-packages\\_pytest\\capture.py:202: OSError\n", "test_name": "test_case7", "rerun": "0"}, "1": {"status": "ERROR", "message": "@pytest.fixture\n    def common_function():\n>       name = input(\"Enter your name: \")\n\ntest_demo3.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <_pytest.capture.DontReadFromInput object at 0x0000015F7FCABDD0>, size = -1\n\n    def read(self, size: int = -1) -> str:\n>       raise OSError(\n            \"pytest: reading from stdin while output is captured!  Consider using `-s`.\"\n        )\nE       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n\n..\\venv\\Lib\\site-packages\\_pytest\\capture.py:202: OSError\n", "test_name": "test_case5", "rerun": "0"}, "2": {"status": "ERROR", "message": "@pytest.fixture\n    def common_function():\n>       name = input(\"Enter your name: \")\n\ntest_demo3.py:6: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <_pytest.capture.DontReadFromInput object at 0x0000015F7FCABDD0>, size = -1\n\n    def read(self, size: int = -1) -> str:\n>       raise OSError(\n            \"pytest: reading from stdin while output is captured!  Consider using `-s`.\"\n        )\nE       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n\n..\\venv\\Lib\\site-packages\\_pytest\\capture.py:202: OSError\n", "test_name": "test_case6", "rerun": "0"}}, "suite_name": "test_demo3.py"}}}, "date": "July 06, 2023", "start_time": 1688633168.525331, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "3", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}